### ISSUE TITLE
no main.dart how to run?

### ISSUE THREAD

**Issue by lucasjinreal** [giantsol/Yellow-Box#52]
no main.dart how to run?

**Comment by giantsol** [comment]
Hi @jinfagang,
There's `Main.dart` file and you can find the `main()` function there.
The file name doesn't strictly have to be `main.dart`, as long as there's a `main()` function.
Thanks :)

**Comment by lucasjinreal** [comment]
@giantsol Not me need main.dart. But flutter run will try to find this one, otherwise how did u run it?

**Comment by giantsol** [comment]
@jinfagang Oh I just used Android Studio and pressed run button. I tried `flutter run` from cmd now and it seems to work fine.
Perhaps IDE has changed some run configurations for me :)
